---
# Run with ansible-playbook <filename> -u ubuntu
#   (make sure to add the IPs of machines you want to manage to /etc/ansible/hosts first)

- hosts: all
  
  vars:
    ansible_ssh_user: ubuntu
    become: yes
    become_user: root
    become_method: sudo

  tasks:
    # Install python
    - name: Install python
      raw: "apt-get -y install python"

    - name: Fancy way of doing authorized_keys
    authorized_key: user=root
                    exclusive=no
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub')  }}"

    #- name: Create /root/.ssh
    #  file: path=/root/.ssh state=directory mode=0700

    #- name: Create /root/.ssh/authorized_keys from our local ssh pubkey
    #  lineinfile: dest=/root/.ssh/authorized_keys line="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

